---

- hosts: controllers
  tasks:
    - name: Apply sealed secrets controller
      shell: kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.19.4/controller.yaml
    - name: Install kubeseal
      shell: |
        wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.19.4/kubeseal-0.19.4-linux-amd64.tar.gz
        tar -xvzf kubeseal-0.19.4-linux-amd64.tar.gz kubeseal
        sudo install -m 755 kubeseal /usr/local/bin/kubeseal
        rm kubeseal-0.19.4-linux-amd64.tar.gz
        rm kubeseal