#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- Use an initContainer to download the Flood web ui
# Set UI with env `TRANSMISSION_WEB_HOME` set to `/config/flood-for-transmission/`
# @default -- See values.yaml
initContainers:
  custom-webui:
    name: custom-webui
    image: curlimages/curl:7.76.1
    command:
    - "/bin/sh"
    - "-c"
    - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 568
      runAsGroup: 568

# -- environment variables. See [image docs](https://github.com/k8s-at-home/container-images/tree/main/apps/transmission/settings.json.tmpl) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Path in container where the Web UI is located
  TRANSMISSION_WEB_HOME: /config/flood-for-transmission/
  # -- Password to access the Web UI
  TRANSMISSION_RPC_PASSWORD: CHANGEME

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: transmission.domu.casa
        paths:
          - path: "/"
    tls:
      - hosts:
          - transmission.domu.casa
        secretName: domu-casa-tls

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    accessMode: ReadWriteMany
    size: 256M

  downloads:
    enabled: true
    mountPath: /downloads
    accessMode: ReadWriteMany
    size: 100Gi

  watch:
    enabled: false
    mountPath: /watch
