---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domu-casa
  namespace: home-services
spec:
  secretName: domu-casa-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.domu.casa"
  dnsNames:
    - "*.domu.casa"
