---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domu-casa
  namespace: portainer
spec:
  secretName: portainer-domu-casa-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "portainer.domu.casa"
  dnsNames:
    - "portainer.domu.casa"
